### ISSUE TITLE
Incompatible with Forge 25 b110

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [dmillerw/MineMenu#51]
```
[15:30:54] [modloading-worker-1/ERROR]: Exception caught during firing event: net.minecraftforge.fml.common.ObfuscationReflectionHelper.remapName(Ljava/lang/String;)Ljava/lang/String;
	Index: 1
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$1330/1065262317@140a0846
java.lang.NoSuchMethodError: net.minecraftforge.fml.common.ObfuscationReflectionHelper.remapName(Ljava/lang/String;)Ljava/lang/String;
	at dmillerw.menu.helper.KeyReflectionHelper.gatherFields(KeyReflectionHelper.java:14)
	at dmillerw.menu.MineMenu.setupClient(MineMenu.java:46)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:209)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:201)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:266)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:105)
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source)
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source)
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:111)
	at net.minecraftforge.fml.ModList.lambda$null$9(ModList.java:120)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
	at java.util.concurrent.CountedCompleter.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source)
	at java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at net.minecraftforge.fml.ModList.lambda$dispatchParallelEvent$10(ModList.java:120)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

[15:30:54] [Forge Version Check/INFO]: [forge] Starting version check at https://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[15:30:54] [modloading-worker-1/ERROR]: Caught exception during event FMLClientSetupEvent dispatch for modid minemenu
java.lang.NoSuchMethodError: net.minecraftforge.fml.common.ObfuscationReflectionHelper.remapName(Ljava/lang/String;)Ljava/lang/String;
	at dmillerw.menu.helper.KeyReflectionHelper.gatherFields(KeyReflectionHelper.java:14) ~[?:1.13.2-1.7.1]
	at dmillerw.menu.MineMenu.setupClient(MineMenu.java:46) ~[?:1.13.2-1.7.1]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:209) ~[eventbus-0.8.1-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:201) ~[eventbus-0.8.1-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:266) ~[eventbus-0.8.1-service.jar:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:105) ~[?:25.0]
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source) ~[?:1.8.0_201]
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source) ~[?:1.8.0_201]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:111) ~[?:?]
	at net.minecraftforge.fml.ModList.lambda$null$9(ModList.java:120) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_201]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_201]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_201]
	at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) ~[?:1.8.0_201]
	at java.util.concurrent.CountedCompleter.exec(Unknown Source) ~[?:1.8.0_201]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_201]
	at java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source) ~[?:1.8.0_201]
	at java.util.concurrent.ForkJoinTask.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source) ~[?:1.8.0_201]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source) ~[?:1.8.0_201]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_201]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_201]
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[?:1.8.0_201]
	at net.minecraftforge.fml.ModList.lambda$dispatchParallelEvent$10(ModList.java:120) ~[?:?]
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source) [?:1.8.0_201]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_201]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_201]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_201]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_201]
[15:30:54] [Client thread/FATAL]: Failed to complete lifecycle event SIDED_SETUP, 1 errors found
```

**Comment by Pythonic-Rainbow** [comment]
AppleSkins suffer from similar crash

**Comment by GirafiStudios** [comment]
Thank you for your report!
CPW apparently changed a few things related to reflection in 25.0.110.
A new version will be out on CurseForge as soon as it get accepted.
Please note that the new version will only work on 25.0.110+, and not on older versions.

**Comment by 0x4B776F6B4353** [comment]
Thanks.

**Comment by 0x4B776F6B4353** [comment]
Sorry @GirafiStudios I updated to the latest artifact , released on 12th April, alongside with Forge b149, but the issue still persists. I can't even find MineMenu in Controls settings.

**Comment by GirafiStudios** [comment]
Are you sure you're evening running Forge? From what I can tell launchers have issues atm. getting Forge versions.

**Comment by Pythonic-Rainbow** [comment]
Retested, now works. Thanks!
